### ISSUE TITLE
修改备案显示条件&多语言支持

### ISSUE THREAD

**Issue by Monodesu** [desu-life/desu-life#11]
需要将icp显示判断从来源ip改为使用servername。
并且footer再加一行说明，选择语言，
如果来源域名是desu.life就根据浏览器语言展示网站的语言，
cn.desu.life就什么都不显示，不给切换，直接默认简体中文+显示备案信息。
并且中国大陆以外的用户通过页脚的地域切换语言/地区时，不显示China Mainland

*中国大陆用户访问desu.life会被重定向至cn.desu.life
*其他地区用户无法访问cn.desu.life

**Comment by jz0ojiang** [comment]
# 修改备案显示条件

已将备案显示条件由 query + cookie + 来源 IP 更改为 query + domain 检测

1de449bbba98a10348e07c2e36e4803aa1ed96a2 ***\* 已将区域判断从 `footer.vue` 移动到 `siteStateStore`***

**Comment by jz0ojiang** [comment]
# i18n

新增 `vue-i18n` 与 `@intlify/unplugin-vue-i18n/vite`。

现在可以通过修改 `src/locales/` 下的文件进行国际化语言。

新增语言后，需要执行以下步骤：

1. 前往 `src/i18n/index.ts` 中为 `messages` 添加引用。
2. 前往 `src/components/home/footer.vue` 为语言列表 `Languages` 添加选项。
3. 不要忘了更新 `public/device/*lang/` 下的设备 modal 内容。

***目前 en 和 ja 语言版本由 GPT-4.0 根据 zh-Hans 翻译得出。若有语义错误，请提交 PR 或 issue 进行修改或指出。***

在 `footer.json` 中新增可以解析的标签：
```html
<i18n>path.to.i18n.text
```

**Comment by jz0ojiang** [comment]
如有新的相关需求请重新开启该 issue 或提交新的 issue
