### ISSUE TITLE
i18n问题

### ISSUE THREAD

**Issue by Monodesu** [desu-life/desu-life#12]
官网在系统语言为不支持的语言时，会默认显示中文，而不是英文，并且没有很明显的语言选择引导

**Comment by jz0ojiang** [comment]
## 首次进入网站

![image](https://github.com/user-attachments/assets/8d0717bb-2e22-41f4-9a8a-0491b17bd5c8)

## 切换语言后

![image](https://github.com/user-attachments/assets/d3290c73-e922-4f9f-b061-9b2a575684e1)

位于 [`/src/locales/<lang>.ts:notify.lang`](https://github.com/desu-life/desu-life/commit/3a445b6a980bd3ec9a0969bfdca84bf21c22007d#diff-9655675aa170422d397e0c2c554bff9ab02cd7ec0411f0bfa45341d380bf1f01) 下的 i18n 示例：

```typescript
lang: {
    title: "语言已切换",
    content_first: "检测到您位于{region}，已自动将语言设置为{lang}。如需更改，请在页脚修改语言设置。",
    content: "已成功将语言切换为@:{'lang.languageName'}。",
    countdown: "此提示将在 {countdown} 秒后自动关闭。"
}
```

**Comment by jz0ojiang** [comment]
如有新的相关需求请重新开启该 issue 或提交新的 issue
