### ISSUE TITLE
i18n新增语言&单独的支持页面

### ISSUE THREAD

**Issue by Monodesu** [desu-life/desu-life#13]
i18n: 需新增韩文

单独的支持页面：抛弃meowpad_v2.md与meowpad_v2_se.md，主页超链接点击不再跳出弹窗，而跳转至新的支持页面，配置器除了v1需要特殊分离以外（可以做一个折叠页折起来，v1已不再重要），其余设备均共用同一个配置器。

**Comment by Monodesu** [comment]
新的表述文本：


# desu.life device 交流群

**一群：722122663 | 二群：309702152**

# 通用配置器

## 本地下载

* [windows-msi](https://assets.desu.life/device/app/resources/MeowpadConfiguratorForV2_v1.0.3_windows.msi)
* [macos-app](https://assets.desu.life/device/app/resources/MeowpadConfiguratorForV2_v1.0.3_macos_app.zip)
* [macos-dmg](https://assets.desu.life/device/app/resources/MeowpadConfiguratorForV2_v1.0.3_macos.dmg)
* [linux-deb](https://assets.desu.life/device/app/resources/MeowpadConfiguratorForV2_v1.0.3_linux_deb.zip)
* [linux-appimage](https://assets.desu.life/device/app/resources/MeowpadConfiguratorForV2_v1.0.3_linux.AppImage)

*仅适用于Meowpad V2及之后发售的产品。

# 下载固件

## Pure 64

[0.1.2](https://assets.desu.life/device/firmware/resources/pure64/pure64-firmware-v0.1.2.hex)

## Meowpad V2

[0.1.1](https://desu.life/device/firmware/download/Meowpad_v2/Meowpad_v2_0.1.1.bin)

# Meowpad V1

产品说明及固件升级教程： [资讯站](https://info.desu.life/?p=338)

## Meowpad v1 配置器（0.3.1）

[win x64](https://desu.life/device/app/download/Meowpad_v1/MeowpadConfigurator_0.3.1_x64_en-US.msi.zip)  | [macos](https://desu.life/device/app/download/Meowpad_v1/MeowpadConfigurator_0.3.1_macos-app.zip) | [linux deb](https://desu.life/device/app/download/Meowpad_v1/MeowpadConfigurator_0.3.1_amd64.deb.zip)

## Meowpad v1 固件

meowpad_v1.1_hs固件 (Hall Effect release 1.0.0 patch 23090101)： [本地下载](https://desu.life/device/firmware/download/Meowpad_v1/meowpad_v1_app_hs_edition_1.0.0_ptach_23090101.bin)

meowpad_v1.0固件 (Mechanical beta 0.1.6)： [本地下载](https://desu.life/device/firmware/download/Meowpad_v1/meowpad_v1_app_0.1.6.bin)

meowpad_v1固件升级套件 (dfu-util)：[本地下载](https://desu.life/device/firmware/download/Meowpad_v1/firmware_updater.zip)

**Comment by jz0ojiang** [comment]
i18n 新增韩文 db7012a81e02fc6fbaffe6dcba13e7683f9e602d
