### ISSUE TITLE
html锚点跳转不正常

### ISSUE THREAD

**Issue by Monodesu** [desu-life/desu-life#8]
首次访问https://desu.life/#meowpad不会跳转，再次回车访问才正常跳转。
还需要把meowpad改为device

**Comment by jz0ojiang** [comment]
commit: bb2aa1e6bffde7253f68cb77b42ce7370c81e98f

现在通过直接访问 link#id 或 link?to=id 均可直接跳转到对应锚点

meowpad.vue meowpad/* 已更名为 device
（但 asserts/meowpad 不变）
