### ISSUE TITLE
备案信息显示机制

### ISSUE THREAD

**Issue by Monodesu** [desu-life/desu-life#9]
判断传入ip，如为大陆ip，则在页脚显示备案信息，否则隐藏
（传入ip不为大陆默认走的是cf，大陆走的国内cdn）

**Comment by jz0ojiang** [comment]
不推荐根据条件判断显示/隐藏备案号

如果在审查网页的时候走了cfcdn导致备案号被隐藏可能会造成不必要的麻烦

如果是不同域名/镜像站等情况，可以通过ip判断弹出提示“是否跳转到国内/国际站点”

-----

关于备案显示：

在 [/public/footer.json](https://github.com/desu-life/desu-life/blob/main/public/footer.json) 处已经预留了显示备案号的页脚

您可以前往编辑该文件的 "center" 部分按照以下格式填写

```json
"center": [
"<link>[区ICP备123456790](https://linkhere)"
]
```

以 `<link>`起始的值将被解析为超链接

-----

如果还有什么修改意见，可以继续在该 issue 下留言

**Comment by jz0ojiang** [comment]
已于 7e4f8c48753b1ed39605ab02219d14fe3d46df1d 与 3c41e183dd83edbfc106445ef7ee7912e0022071 commits 中实现该需求，如有新的相关需求请重新开启该 issue 或提交新的 issue
